/*Count and Say problem -
The nth term is generated by reading (n-1)th term.
    The first term is "1"
    Second term is "11", generated by reading first term as "One 1" (There is one 1 in previous term)
    Third term is "21", generated by reading second term as "Two 1"
    Fourth term is "1211", generated by reading third term as "One 2 One 1" and so on
*/

import java.util.*;
class Main {
    public static String nextTerm(String prev) {
        StringBuilder curr = new StringBuilder();
        int count = 1;
        
        for (int i = 1; i < prev.length(); i++) {
            if (prev.charAt(i) == prev.charAt(i - 1)) {
                count++;
            } else {
                curr.append(count);
                curr.append(prev.charAt(i - 1));
                count = 1;
            }
        }
        //apending last char's count and char
        curr.append(count);
        curr.append(prev.charAt(prev.length() - 1));
        
        return curr.toString();
    }
    
    public static String countAndSay(int n) {
        if (n == 1)
            return "1";

        String prev = countAndSay(n - 1);
        return nextTerm(prev);
    }
    
    public static void main(String[] args) {
        int n = 2;
        System.out.println(countAndSay(n));
    }
}
